### ISSUE TITLE
Dealing with the DMA-frame-boundary problem

### ISSUE THREAD

**Issue by dinkc64** [elzo-d/LakeSnes#11]
This issue is just a place to discuss possible solutions for the DMA-frame-boundary issue.  That is, where a DMA operation causes the frame to extend past its ending.

Noticable problems this causes are little clicks in the audio.
for example:
Actraiser 2 as the music starts and the screen fades in (after pr #10 applied)
Tales of Phantasia is a more severe example of the problem.
(of course, there are games that don't rely on pr#10 to be first applied, I just don't remember them as I'm new to SNES games)

**Comment by dinkc64** [comment]
Possible solution #1:
DMA-stating, when we get to the frame boundary: save the dma-in-progress to a couple variables, then restore & continue them @ the beginning of next frame.

Effects
Positive: it works, frame size is always perfect, audio problems disappear

Negative: since we're half-way through an opcode on the main processor when the dma happens, this opcode finishes, and the dma is restored after several cycles(ie: the end of the opcode) have passed.  It doesn't seem to cause any problem in-game, though, due to the cycle offset, it is a little hacky.

note: I'll post the code to this a little later today, sorry for the delay.

**Comment by angelo-wf** [comment]
A possible solution that would work with the current queue-based audio playback and should not be hard to implement would be to add a way to query the exact amount of generated samples since the previous `getSamples`-call. The main loop could then ask for only the newly generated ones, and not (as happens now) also get duplicates of previous samples (which is the cause of the popping/clicks). This wouldn't require any changes to the actual emulation at all.

I don't know when I will have the time, but I do want to look into this (and look at your PR #10 as well).

**Comment by dinkc64** [comment]
Hi angelo-wf,
That's a good idea, and it was one of the first things I tried, but, it doesn't help when the dma goes over a couple frames while music is playing (for example, Actraiser 2).  To be fair, even Mesen2 clicks here.  This is what lead me to the dma-freeze-and-restart idea.  Maybe we can come up with a better solution.  

While working on emu-projects over the years I've learned something: there are a hundred ways to make a fix.  12 will work (with side effects) and 1 will be the perfect fix.  Let's find the perfect fix.  :)

best regards,
- dink

**Comment by dinkc64** [comment]
After many tests and lots of brainstorming....
The dma freeze-and-restart idea would have been a winner if it weren't for the cycle-discrepancy.  Time to toss this idea out completely :/

So, my next idea to tackle this is some sort of queue:
4 audio buffers/4 video buffers, [frame_number&3] will always be the latest.  If the game runs dma for 3 frames then the next 3 times a frame is run, it will just return until we're caught up.

best regards,
- dink

**Comment by dinkc64** [comment]
Think I'll give this one a break....

**Comment by dinkc64** [comment]
@angelo-wf Hi,
been working on cx4 emulation, got the mapper & about half of the instructions impl'd so far!  Megman X2 doesn't fully boot yet, but it doesn't error-out anymore either, yay.

so, my question is: should I do this any differently?
I've modified cart.cpp and snes_other.cpp to use cart->type of 4 for the cx4 mappings.  in snes_other.cpp, right above "// load it", I added this:
  // coprocessor check
  if (headers[used].exCoprocessor == 0x10) {
	  headers[used].cartType = 4; // cx4
  }
This cart type is basically lorom + cx4 chip mapped at 0-3f,80-bf,6000-7fff

best regards,
- dink

**Comment by angelo-wf** [comment]
Using new cart-types for coprocessors is indeed how I imagined it being used. I would probably do the coprocessor check in `readHeader`, as that is where types 1-3 are also set. Note that I did had some ideas about making some changes to how cart-loading and the cart-interface works (defining and checking for all types/coprocessors, and changing from the switch-cases in the read/write functions to function pointers and functions for each cart-type) but haven't gotten around to it yet. But it shouldn't be a problem to (eventually) do this after CX4 support is added.

As for the frame-crossing DMA's, keeping track of multiple frame/audio-buffers would probably be the best way to keep the current `runFrame` based interface while always providing full frames/sample buffers. I want to try and look into this myself as well.

**Comment by dinkc64** [comment]
Wahoo! This bug is dead :)
https://github.com/dinkc64/LakeSnes/commit/a2d36931a9b7812f4a8cd1494a5fe01318a8e835

**Comment by angelo-wf** [comment]
I have decided to archive this repository. As you probably noticed due to my inactivity, some motivational/mental issues mean I don't see myself working on it any further. I have linked your fork in the readme, as it seems to be the most active one and has all the updates you made to it, like the CX4 support and optimisations.

(You might want to pull this change in your fork and then remove the notice again, so it doesn't stay at '1 commit behind' forever.)
